routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/not-ready', 'HomeController@launchingSoon');
Route::get('/', 'HomeController@index')->name('landing');
Auth::routes(['verify' => true]);

Route::get('/home', function() {
    return redirect('/admin');
})->name('home');

require_once('Routes/admin.php');
require_once('Routes/about.php');
require_once('Routes/product.php');
require_once('Routes/marketing.php');
require_once('Routes/contact-us.php');


Route::get('/admin-run-migrations', function() {
    return Artisan::call('migrate', ["--force" => true ]);
})->middleware('auth');

Route::get('test-mail', function() {
    $order = \App\Models\Order::find(59);
    if ($order->product->type == "product") {
        $url = route('my-orders.index', ["tab" => "received"]);
    } else {
        $url = route('admin.activation.index');
    }

    \App\Http\Helpers\Helpers::notifyRecievedOrder($order, $url);

    return 'Email sent successfully.';
});


Route::get('fix-tree', function() {
    \App\Models\Membership::fixTree();
});

Route::get('switch-from-free/{user_id}', function($user_id) {
    \App\Http\Helpers\Helpers::earnReferralCommission($user_id, true);
});

Route::get('fix-commissions/{username}', function ($username) {

    $user = \App\User::whereUsername($username)->first();
    if (!$user && $user->role_id != 1) {
        return "Member not found.";
    }
    
    \DB::transaction(function () use ($user) {
        
        
        $earnings = \App\Http\Helpers\Helpers::computeEarnings($user->membership->id);
        $encashments = $user->membership->encashment_histories()->whereIn("status", ["pending", "complete"])->sum("amount");
        $available_commissions = $earnings - $encashments;
        $user->membership->update([
            "available_commissions" => $available_commissions
        ]);
    });

});


Route::group(['prefix' => 'contact-us', 'as' => 'contact-us.', 'namespace' => 'Admin'], function() {
    Route::post('/postMessage', ['as' => 'post-message', 'uses' => 'ContactUsController@postMessage']);
});

Route::get('admin-members-claim-bonus', function() {
    $now = \Carbon\Carbon::now();

    $secondDayOfThisMonth = $now->firstOfMonth()->addDays(1)->toDateString();
    $bonuses = \App\Models\Earning::whereNull("added_to_wallet_at")
                                ->whereIn("type", ["unilevel", "indirect referral"])
                                ->whereDate("valid_at", "<", $secondDayOfThisMonth)
                                ->get();

    $membersToClaimBonus = \App\Models\Membership::whereHas('earnings', function($q) use ($secondDayOfThisMonth) {
                                        $q->whereNull('added_to_wallet_at')
                                            ->whereIn('type', ['unilevel', 'indirect referral'])
                                            ->whereDate('valid_at', '<', $secondDayOfThisMonth);
                                    })->get();
                                    
    \DB::transaction(function () use ($membersToClaimBonus) {
        $membersToClaimBonus->each(function($member) {
            \App\Http\Helpers\TransactionsHelper::claimBonus($member, 2);
        });
    });
});

Route::get('fix-wrong-valid-at', function() {
    $earnings = \App\Models\Earning::whereNotNull('valid_at')
                                ->whereIn('type', ['unilevel', 'indirect referral'])
                                ->select('id', 'type', 'member_id', 'added_to_wallet_at', 'created_at', 'valid_at')
                                ->whereRaw("DATE_FORMAT(DATE_ADD(created_at, interval 1 MONTH), '%m') <> DATE_FORMAT(valid_at, '%m')")
                                ->get();

    \DB::beginTransaction();

    try {

        foreach ($earnings as $earning) {
            $valid_at = \Carbon\Carbon::parse($earning->created_at)->firstOfMonth()->addMonths(1);
            $earning->valid_at = $valid_at->toDateTimeString();
            $earning->save();
        };

        \DB::commit();
    } catch (\Throwable $th) {
        \DB::rollback();
        throw $th;
    }
});

Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'PostController@index']);
    Route::get('create', ['as' => 'create', 'uses' => 'PostController@create']);
    Route::get('{post}', ['as' => 'edit', 'uses' => 'PostController@edit']);
    Route::post('', ['as' => 'store', 'uses' => 'PostController@store']);
    Route::post('{post}', ['as' => 'update', 'uses' => 'PostController@update']);
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'description'
    ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        $posts = Post::all();

        return view('posts.index', compact('posts'));
    }

    public function create()
    {
        return view('posts.create');
    }
    
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required'
        ]);

        Post::create([
            'title' => $request->title,
            'description' => $request->description
        ]);

        return redirect()->route('posts.index')->withSuccess('Post successfully created.');
    }
    
    public function update(Post $post, Request $request)
    {
        $request->validate([
            'title' => 'required'
        ]);

        $post->update([
            'title' => $request->title,
            'description' => $request->description
        ]);

        return redirect()->route('posts.index')->withSuccess('Post successfully updated.');
    }
}

resources/views/posts/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MJ Premium Posting</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <div class="h2">Posts &raquo; <small>Add post</small></div>
            </div>
            <div class="card-body">
                <form action="{{ route('posts.store') }}" method="post">
                    @csrf
                    @method('post')
                    <div class="form-group mb-3">
                        <label for="title">Title</label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ old('title') }}">
                    </div>
                    
                    <div class="form-group mb-3">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" cols="30" rows="5" class="form-control">{{ old('description') }}</textarea>
                    </div>
                    <a class="btn btn-secondary" href="{{ route('posts.index') }}" type="button">Cancel</a>
                    <button class="btn btn-primary" >Save</button>
                </form>
            </div>
        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/posts/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MJ Premium Posting</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-header">
                <div class="h2">Posts &raquo; <small>Edit post</small></div>
            </div>
            <div class="card-body">
                <form action="{{ route('posts.update', $post) }}" method="post">
                    @csrf
                    @method('post')
                    <div class="form-group mb-3">
                        <label for="title">Title</label>
                        <input type="text" id="title" name="title" class="form-control" value="{{ old('title', $post->title) }}">
                    </div>
                    
                    <div class="form-group mb-3">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" cols="30" rows="5" class="form-control">{{ old('description', $post->description) }}</textarea>
                    </div>
                    <a class="btn btn-secondary" href="{{ route('posts.index') }}" type="button">Cancel</a>
                    <button class="btn btn-primary">Save Changes</button>
                </form>
            </div>
        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

resources/views/posts/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MJ Premium Posting</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        @if(session()->has('success'))
            <div class="alert alert-success">
                {!! session()->get('success') !!}
            </div>
        @endif

        <div class="card">
            <div class="card-header">
                <div class="h2">Posts</div>
            </div>
            <div class="card-body">
                <a href="{{ route("posts.create") }}" class="btn btn-primary mb-3">Add Post</a>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Created at</th>
                                <th>Updated at</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($posts as $item)
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ $item->description ?? 'No description to display.' }}</td>
                                    <td>{{ $item->created_at->format('m/d/Y h:i A') }}</td>
                                    <td>{{ $item->updated_at->format('m/d/Y h:i A') }}</td>
                                    <td>
                                        <a href="{{ route('posts.edit', $item) }}" class="btn btn-primary">Edit</a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6">No posts to display.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>