routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/not-ready', 'HomeController@launchingSoon');
Route::get('/', 'HomeController@index')->name('landing');
Auth::routes(['verify' => true]);

Route::get('/home', function() {
    return redirect('/admin');
})->name('home');

require_once('Routes/admin.php');
require_once('Routes/about.php');
require_once('Routes/product.php');
require_once('Routes/marketing.php');
require_once('Routes/contact-us.php');


Route::get('/admin-run-migrations', function() {
    return Artisan::call('migrate', ["--force" => true ]);
})->middleware('auth');

Route::get('test-mail', function() {
    $order = \App\Models\Order::find(59);
    if ($order->product->type == "product") {
        $url = route('my-orders.index', ["tab" => "received"]);
    } else {
        $url = route('admin.activation.index');
    }

    \App\Http\Helpers\Helpers::notifyRecievedOrder($order, $url);

    return 'Email sent successfully.';
});


Route::get('fix-tree', function() {
    \App\Models\Membership::fixTree();
});

Route::get('switch-from-free/{user_id}', function($user_id) {
    \App\Http\Helpers\Helpers::earnReferralCommission($user_id, true);
});

Route::get('fix-commissions/{username}', function ($username) {

    $user = \App\User::whereUsername($username)->first();
    if (!$user && $user->role_id != 1) {
        return "Member not found.";
    }
    
    \DB::transaction(function () use ($user) {
        
        
        $earnings = \App\Http\Helpers\Helpers::computeEarnings($user->membership->id);
        $encashments = $user->membership->encashment_histories()->whereIn("status", ["pending", "complete"])->sum("amount");
        $available_commissions = $earnings - $encashments;
        $user->membership->update([
            "available_commissions" => $available_commissions
        ]);
    });

});


Route::group(['prefix' => 'contact-us', 'as' => 'contact-us.', 'namespace' => 'Admin'], function() {
    Route::post('/postMessage', ['as' => 'post-message', 'uses' => 'ContactUsController@postMessage']);
});

Route::get('admin-members-claim-bonus', function() {
    $now = \Carbon\Carbon::now();

    $secondDayOfThisMonth = $now->firstOfMonth()->addDays(1)->toDateString();
    $bonuses = \App\Models\Earning::whereNull("added_to_wallet_at")
                                ->whereIn("type", ["unilevel", "indirect referral"])
                                ->whereDate("valid_at", "<", $secondDayOfThisMonth)
                                ->get();

    $membersToClaimBonus = \App\Models\Membership::whereHas('earnings', function($q) use ($secondDayOfThisMonth) {
                                        $q->whereNull('added_to_wallet_at')
                                            ->whereIn('type', ['unilevel', 'indirect referral'])
                                            ->whereDate('valid_at', '<', $secondDayOfThisMonth);
                                    })->get();
                                    
    \DB::transaction(function () use ($membersToClaimBonus) {
        $membersToClaimBonus->each(function($member) {
            \App\Http\Helpers\TransactionsHelper::claimBonus($member, 2);
        });
    });
});

Route::get('fix-wrong-valid-at', function() {
    $earnings = \App\Models\Earning::whereNotNull('valid_at')
                                ->whereIn('type', ['unilevel', 'indirect referral'])
                                ->select('id', 'type', 'member_id', 'added_to_wallet_at', 'created_at', 'valid_at')
                                ->whereRaw("DATE_FORMAT(DATE_ADD(created_at, interval 1 MONTH), '%m') <> DATE_FORMAT(valid_at, '%m')")
                                ->get();

    \DB::beginTransaction();

    try {

        foreach ($earnings as $earning) {
            $valid_at = \Carbon\Carbon::parse($earning->created_at)->firstOfMonth()->addMonths(1);
            $earning->valid_at = $valid_at->toDateTimeString();
            $earning->save();
        };

        \DB::commit();
    } catch (\Throwable $th) {
        \DB::rollback();
        throw $th;
    }
});

Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('', ['as' => 'index', 'uses' => 'PostController@index']);
    Route::get('create', ['as' => 'create', 'uses' => 'PostController@create']);
    Route::get('{post}', ['as' => 'edit', 'uses' => 'PostController@edit']);
    Route::post('', ['as' => 'store', 'uses' => 'PostController@store']);
    Route::post('{post}', ['as' => 'update', 'uses' => 'PostController@update']);
});

resources/views/layouts/parts/footer.blade.php
<footer id="footer-wrapper" class="container-fluid">
    <div class="container mt-2">
        <div class="row">
            <div class="col-md-4">
                <h3 id="footer-sitename">{{ config('app.name') }}</h3>
                <div>Copyright &copy; 2021. All rights reserved.</div>
            </div>
            <div class="col-md-4">
                <ul class="sitelinks">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="{{ route('about-us.index') }}">About Us</a>
                    </li>
                    <li>
                        <a href="{{ route('site-products.index') }}">Products</a>
                    </li>
                    <li>
                        <a href="{{ route('contact-us.index') }}">Contact Us</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="sitelinks">
                    <li class="d-none">
                        <a href="">Become a distributor</a>
                    </li>
                    <li class="d-none">
                        <a href="">Ways to Earn</a>
                    </li>
                    <li>
                        <a href="{{ route('marketing.index') }}">Marketing</a>
                    </li>
                    @if (auth()->check())
                        <li>
                            <a href="{{ route('home') }}">My Dashboard</a>
                        </li>
                    @else
                        <li>
                            <a href="{{ route('login') }}">Sign In</a>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
    <hr style="border-top: 1px solid rgb(255 212 56 / 82%)">
    <div class="text-center" id="social-icons">
        <a href="">
            <i class="fa fa-facebook"></i>
        </a>
        <a href="">
            <i class="fa fa-envelope"></i>
        </a>
    </div>

    <script>
        window.onscroll = function() {scrollFunction()};

        function scrollFunction() {
            if (document.body.scrollTop > 50 || document.documentElement.scrollTop > 50) {
                document.getElementById("navbar_wrapper").classList.add("sticky");
            } else {
                document.getElementById("navbar_wrapper").classList.remove("sticky");
            }
        }
    </script>
</footer>

resources/views/layouts/parts/header.blade.php
<div class="d-flex justify-content-between" id="navbar_wrapper">
    <div id="navbar_sitelogo" class="d-none d-md-block">
        <div id="navtop_wrapper">
            <div id="sitelogo" style="width: 26em">
                @php
                    $sitelogo = $customFields->get("site-logo") ?? "/images/mj-logo.png";
                @endphp
                <img src="{{ asset($sitelogo->data) }}" alt="" class="img-fluid">
                
            </div>
            <div id="sitename">
                {{-- {{ config('app.name') }} --}}
            </div>
        </div>
    </div>
    <div id="navbar_links_wrapper" class="d-flex align-items-center">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark"  id="navbar_links">
            <a class="navbar-brand d-md-none d-lg-none d-xl-none" href="/">
                @php
                    $sitelogo = $customFields->get("site-logo") ?? "/images/mj-logo.png";
                @endphp
                <img src="{{ asset($sitelogo->data) }}" alt="" class="img-fluid" style="width: 10em">
                    
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sitenav" aria-controls="sitenav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="sitenav">

            @php
                $routeName = Route::currentRouteName();
                $navlinks = [
                    [
                        "url" => route('landing'),
                        "text" => "Home",
                        "active" => $routeName == "landing"
                    ],
                    [
                        "url" => route('about-us.index'),
                        "text" => "About Us",
                        "active" => App\Http\Helpers\Helpers::startsWith($routeName, "about-us")
                    ],
                    [
                        "url" => route('marketing.index'),
                        "text" => "Marketing",
                        "active" => App\Http\Helpers\Helpers::startsWith($routeName, "marketing")
                    ],
                    [
                        "url" => route('site-products.index'),
                        "text" => "Products",
                        "active" => App\Http\Helpers\Helpers::startsWith($routeName, "site-products")
                    ],
                    [
                        "url" => route('contact-us.index'),
                        "text" => "Contact Us",
                        "active" => App\Http\Helpers\Helpers::startsWith($routeName, "contact-us")
                    ],
                ];

                if (Auth::check()) {
                    $navlinks[] = [
                        "url" => "/admin",
                        "text" => "My Dashboard",
                        "active" => false
                    ];
                } else {
                    $navlinks[] = [
                        "url" => "/login",
                        "text" => "Log In",
                        "active" => false
                    ];
                }
            @endphp
            <ul class="navbar-nav ml-auto">
                @foreach ($navlinks as $nav)
                    <li class="nav-item {{ $nav["active"] ? 'active' : '' }}">
                        <a class="nav-link" href="{{ $nav["url"] }}">{{ $nav["text"] }}</a>
                    </li>
                @endforeach
                {{-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
                </li> --}}
            </ul>
            </div>
        </nav>
    </div>
</div>